import { openApp, see, hear, onboard, finish } from "./lib.mjs";
const { b, p, errors } = await openApp();
console.log("AUDIT STEP 4 — the screens around the story");
await onboard(p, { level: "+ ck e u r", sibling: "Veda", grown: "Papa" });
await p.click('button[aria-label="Settings"]'); await p.waitForTimeout(700);
await see(p, "4-01 settings");
await p.click("text=Record the sounds"); await p.waitForTimeout(700);
await see(p, "4-02 record the sounds");
await p.click("text=← Back"); await p.waitForTimeout(500);
await p.click("text=Teach the next sound"); await p.waitForTimeout(700);
await see(p, "4-03 teach from settings");
await p.click("text=← Back"); await p.waitForTimeout(500);
await p.click("text=+ Add a family story").catch(() => {}); await p.waitForTimeout(700);
await see(p, "4-04 add a family story");
await p.click("text=← Back").catch(() => {}); await p.waitForTimeout(500);
await p.click("text=Back").catch(() => {}); await p.waitForTimeout(600);
await p.click('button[aria-label="Family"]').catch(() => {}); await p.waitForTimeout(600);
await see(p, "4-05 who is reading");
await p.click("text=Veda"); await p.waitForTimeout(900);
await see(p, "4-06 the little one's home");
await p.click(".big-tile"); await p.waitForTimeout(3000);
await see(p, "4-07 the little one's story");
await finish(b, errors);
